{
    "_downloadFile": [Function _callee7],
    "_loadFromSource": [Function anonymous],
    "_mounted": true,
    "_onChange": [Function anonymous],
    "_onError": [Function anonymous],
    "_prepareFile": [Function _callee3],
    "_reactInternalInstance": {},
    "_reactInternals": {
        "_debugHookTypes": null,
        "_debugID": 14136,
        "_debugNeedsRemount": false,
        "_debugOwner": {
        "_debugHookTypes": [Array],
        "_debugID": 14127,
        "_debugNeedsRemount": false,
        "_debugOwner": [FiberNode],
        "_debugSource": [Object],
        "actualDuration": 56.38970000529662,
        "actualStartTime": 3140794.3606,
        "alternate": null,
        "child": [FiberNode],
        "childLanes": 1,
        "dependencies": [Object],
        "elementType": [Function OpenPdf],
        "firstEffect": [FiberNode],
        "flags": 517,
        "index": 0,
        "key": null,
        "lanes": 0,
        "lastEffect": [Circular],
        "memoizedProps": [Object],
        "memoizedState": [Object],
        "mode": 8,
        "nextEffect": [FiberNode],
        "pendingProps": [Object],
        "ref": null,
        "return": [FiberNode],
        "selfBaseDuration": 8.171399999875575,
        "sibling": null,
        "stateNode": null,
        "tag": 0,
        "treeBaseDuration": 21.51680000219494,
        "type": [Function OpenPdf],
        "updateQueue": [Object]
        },
        "_debugSource": {
        "columnNumber": 7,
        "fileName": "C:\\Users\\gians\\Desktop\\CS\\WebDev\\sikhStuff\\SanthiyaPothi\\src\\openPdf.js",
        "lineNumber": 334
        },
        "actualDuration": 16.87490000203252,
        "actualStartTime": 3140834.1896,
        "alternate": null,
        "child": {
        "_debugHookTypes": null,
        "_debugID": 14209,
        "_debugNeedsRemount": false,
        "_debugOwner": [Circular],
        "_debugSource": [Object],
        "actualDuration": 14.514400001615286,
        "actualStartTime": 3140836.4147,
        "alternate": null,
        "child": [FiberNode],
        "childLanes": 0,
        "dependencies": null,
        "elementType": [Object],
        "firstEffect": null,
        "flags": 1,
        "index": 0,
        "key": null,
        "lanes": 0,
        "lastEffect": null,
        "memoizedProps": [Object],
        "memoizedState": null,
        "mode": 8,
        "nextEffect": null,
        "pendingProps": [Object],
        "ref": null,
        "return": [Circular],
        "selfBaseDuration": 0.3844999996945262,
        "sibling": null,
        "stateNode": null,
        "tag": 11,
        "treeBaseDuration": 3.5205000010319054,
        "type": [Object],
        "updateQueue": null
        },
        "childLanes": 0,
        "dependencies": null,
        "elementType": [Function Pdf],
        "firstEffect": null,
        "flags": 133,
        "index": 1,
        "key": null,
        "lanes": 1,
        "lastEffect": null,
        "memoizedProps": {
            "activityIndicator": <ActivityIndicator … />,
            "activityIndicatorProps": [Object],
            "enableAnnotationRendering": true,
            "enableAntialiasing": true,
            "enablePaging": false,
            "enableRTL": false,
            "fitPolicy": 2,
            "horizontal": false,
            "maxScale": 3,
            "minScale": 1,
            "onError": [Function onError],
            "onLoadComplete": [Function onLoadComplete],
            "onLoadProgress": [Function onLoadProgress],
            "onPageChanged": [Function onPageChanged],
            "onPageSingleTap": [Function onPageSingleTap],
            "onPressLink": [Function onPressLink],
            "onScaleChanged": [Function onScaleChanged],
            "page": 1,
            "password": "",
            "scale": 1,
            "singlePage": false,
            "source": [Object],
            "spacing": 10,
            "style": [Object],
            "trustAllCerts": true,
            "usePDFKit": true
        },
        "memoizedState": {
            "isDownloaded": false,
            "isSupportPDFKit": -1,
            "path": "",
            "progress": 0
        },
        "mode": 8,
        "nextEffect": {
            "_debugHookTypes": [Array],
            "_debugID": 14127,
            "_debugNeedsRemount": false,
            "_debugOwner": [FiberNode],
            "_debugSource": [Object],
            "actualDuration": 56.38970000529662,
            "actualStartTime": 3140794.3606,
            "alternate": null,
            "child": [FiberNode],
            "childLanes": 1,
            "dependencies": [Object],
            "elementType": [Function OpenPdf],
            "firstEffect": [FiberNode],
            "flags": 517,
            "index": 0,
            "key": null,
            "lanes": 0,
            "lastEffect": [Circular],
            "memoizedProps": [Object],
            "memoizedState": [Object],
            "mode": 8,
            "nextEffect": [FiberNode],
            "pendingProps": [Object],
            "ref": null,
            "return": [FiberNode],
            "selfBaseDuration": 8.171399999875575,
            "sibling": null,
            "stateNode": null,
            "tag": 0,
            "treeBaseDuration": 21.51680000219494,
            "type": [Function OpenPdf],
            "updateQueue": [Object]
        },
        "pendingProps": {
            "activityIndicator": <ActivityIndicator … />,
            "activityIndicatorProps": [Object],
            "enableAnnotationRendering": true,
            "enableAntialiasing": true,
            "enablePaging": false,
            "enableRTL": false,
            "fitPolicy": 2,
            "horizontal": false,
            "maxScale": 3,
            "minScale": 1,
            "onError": [Function onError],
            "onLoadComplete": [Function onLoadComplete],
            "onLoadProgress": [Function onLoadProgress],
            "onPageChanged": [Function onPageChanged],
            "onPageSingleTap": [Function onPageSingleTap],
            "onPressLink": [Function onPressLink],
            "onScaleChanged": [Function onScaleChanged],
            "page": 1,
            "password": "",
            "scale": 1,
            "singlePage": false,
            "source": [Object],
            "spacing": 10,
            "style": [Object],
            "trustAllCerts": true,
            "usePDFKit": true
        },
        "ref": [Function ref],
        "return": {"_debugHookTypes": null,
        "_debugID": 14133,
        "_debugNeedsRemount": false,
        "_debugOwner": [FiberNode],
        "_debugSource": [Object],
        "actualDuration": 47.89860000507906,
        "actualStartTime": 3140802.8084,
        "alternate": null,
        "child": [FiberNode],
        "childLanes": 1,
        "dependencies": null,
        "elementType": "RCTView",
        "firstEffect": [FiberNode],
        "flags": 0,
        "index": 0,
        "key": null,
        "lanes": 0,
        "lastEffect": [Circular],
        "memoizedProps": [Object],
        "memoizedState": null,
        "mode": 8,
        "nextEffect": null,
        "pendingProps": [Object],
        "ref": null,
        "return": [FiberNode],
        "selfBaseDuration": 0.08850000007078052,
        "sibling": null,
        "stateNode": [ReactNativeFiberHostComponent],
        "tag": 5,
        "treeBaseDuration": 13.163400002289563,
        "type": "RCTView",
        "updateQueue": null},
        "selfBaseDuration": 2.166700000409037,
        "sibling": null,
        "stateNode": [Circular],
        "tag": 1,
        "treeBaseDuration": 5.687200001440942,
        "type": [Function Pdf],
        "updateQueue": {"baseState": [Object],
        "effects": null,
        "firstBaseUpdate": null,
        "lastBaseUpdate": null,
        "shared": [Object]}
    }
    ,"_unlinkFile": [Function _callee8],
    "context": {},
    "lastRNBFTask": null,
    "props": {"activityIndicator": <ActivityIndicator animating={true} color="blue" hidesWhenStopped={true} size="large" />,
    "activityIndicatorProps": {"color": "#009900",
    "progressTintColor": "#009900"},
    "enableAnnotationRendering": true,
    "enableAntialiasing": true,
    "enablePaging": false,
    "enableRTL": false,
    "fitPolicy": 2,
    "horizontal": false,
    "maxScale": 3,
    "minScale": 1,
    "onError": [Function onError],
    "onLoadComplete": [Function onLoadComplete],
    "onLoadProgress": [Function onLoadProgress],
    "onPageChanged": [Function onPageChanged],
    "onPageSingleTap": [Function onPageSingleTap],
    "onPressLink": [Function onPressLink],
    "onScaleChanged": [Function onScaleChanged],
    "page": 1,
    "password": "",
    "scale": 1,
    "singlePage": false,
    "source": {"uri": "bundle-assets://pdfs/BaiVarra/1)SriRaagKiVaarMahala4.pdf"},
    "spacing": 10,
    "style": {"borderRadius": 25,
    "height": "89%",
    "width": "100%"},
    "trustAllCerts": true,
    "usePDFKit": true},
    "refs": {},
    "setNativeProps": [Function anonymous],
    "state": {
        "isDownloaded": false,
        "isSupportPDFKit": -1,
        "path": "",
        "progress": 0
    },
    "updater": {
        "enqueueForceUpdate": [Function enqueueForceUpdate],
        "enqueueReplaceState": [Function enqueueReplaceState],
        "enqueueSetState": [Function enqueueSetState],
        "isMounted": [Function isMounted]
    }
}
