{
    "_dispatchInstances": {
        "_debugHookTypes": null,
        "_debugID": 31294,
        "_debugNeedsRemount": false,
        "_debugOwner": {
            "_debugHookTypes": [Array],
            "_debugID": 31288,
            "_debugNeedsRemount": false,
            "_debugOwner": [FiberNode],
            "_debugSource": [Object],
            "actualDuration": 1.3340999999199994,
            "actualStartTime": 444208.4736,
            "alternate": [FiberNode],
            "child": [FiberNode],
            "childLanes": 0,
            "dependencies": null,
            "elementType": [Function InternalTextInput],
            "firstEffect": [Circular],
            "flags": 5,
            "index": 0,
            "key": null,
            "lanes": 0,
            "lastEffect": [FiberNode],
            "memoizedProps": [Object],
            "memoizedState": [Object],
            "mode": 8,
            "nextEffect": null,
            "pendingProps": [Object],
            "ref": null,
            "return": [FiberNode],
            "selfBaseDuration": 0.5415999999968335,
            "sibling": null,
            "stateNode": null,
            "tag": 0,
            "treeBaseDuration": 1.017200000002049,
            "type": [Function InternalTextInput],
            "updateQueue": [Object]
        },
        "_debugSource": {
            "columnNumber": 7,
            "fileName": "C:\\Users\\gians\\Desktop\\CS\\WebDev\\sikhStuff\\SanthiyaPothi\\node_modules\\react-native\\Libraries\\Components\\TextInput\\TextInput.js",
            "lineNumber": 1121
        },
        "actualDuration": 0.25760000001173466,
        "actualStartTime": 444209.5192,
        "alternate": {
            "_debugHookTypes": null,
            "_debugID": 31294,
            "_debugNeedsRemount": false,
            "_debugOwner": [FiberNode],
            "_debugSource": [Object],
            "actualDuration": 0.15590000001247972,
            "actualStartTime": 444170.704,
            "alternate": [Circular],
            "child": null,
            "childLanes": 0,
            "dependencies": null,
            "elementType": "AndroidTextInput",
            "firstEffect": null,
            "flags": 132,
            "index": 0,
            "key": null,
            "lanes": 0,
            "lastEffect": null,
            "memoizedProps": [Object],
            "memoizedState": null,
            "mode": 8,
            "nextEffect": null,
            "pendingProps": [Object],
            "ref": [Function forwardRef],
            "return": [FiberNode],
            "selfBaseDuration": 0.10490000003483146,
            "sibling": null,
            "stateNode": [ReactNativeFiberHostComponent],
            "tag": 5,
            "treeBaseDuration": 0.10490000003483146,
            "type": "AndroidTextInput",
            "updateQueue": null
        },
        "child": null,
        "childLanes": 0,
        "dependencies": null,
        "elementType": "AndroidTextInput",
        "firstEffect": null,
        "flags": 132,
        "index": 0,
        "key": null,
        "lanes": 0,
        "lastEffect": null,
        "memoizedProps": {
            "accessible": true,
            "allowFontScaling": true,
            "autoCapitalize": "sentences",
            "blurOnSubmit": true,
            "children": undefined,
            "disableFullscreenUI": undefined,
            "focusable": true,
            "forwardedRef": null,
            "mostRecentEventCount": 5,
            "onBlur": [Function _onBlur],
            "onChange": [Function _onChange],
            "onClick": [Function onClick],
            "onFocus": [Function _onFocus],
            "onResponderGrant": [Function onResponderGrant],
            "onResponderMove": [Function onResponderMove],
            "onResponderRelease": [Function onResponderRelease],
            "onResponderTerminate": [Function onResponderTerminate],
            "onResponderTerminationRequest": [Function onResponderTerminationRequest],
            "onScroll": [Function _onScroll],
            "onSelectionChange": [Function _onSelectionChange],
            "onStartShouldSetResponder": [Function onStartShouldSetResponder],
            "onSubmitEditing": [Function onSubmitEditing],
            "placeholder": "exp: Folder 1",
            "rejectResponderTermination": true,
            "selection": null,
            "style": [Array],
            "text": "",
            "textBreakStrategy": undefined,
            "underlineColorAndroid": "transparent"
        },
        "memoizedState": null,
        "mode": 8,
        "nextEffect": null,
        "pendingProps": {
            "accessible": true,
            "allowFontScaling": true,
            "autoCapitalize": "sentences",
            "blurOnSubmit": true,
            "children": undefined,
            "disableFullscreenUI": undefined,
            "focusable": true,
            "forwardedRef": null,
            "mostRecentEventCount": 5,
            "onBlur": [Function _onBlur],
            "onChange": [Function _onChange],
            "onClick": [Function onClick],
            "onFocus": [Function _onFocus],
            "onResponderGrant": [Function onResponderGrant],
            "onResponderMove": [Function onResponderMove],
            "onResponderRelease": [Function onResponderRelease],
            "onResponderTerminate": [Function onResponderTerminate],
            "onResponderTerminationRequest": [Function onResponderTerminationRequest],
            "onScroll": [Function _onScroll],
            "onSelectionChange": [Function _onSelectionChange],
            "onStartShouldSetResponder": [Function onStartShouldSetResponder],
            "onSubmitEditing": [Function onSubmitEditing],
            "placeholder": "exp: Folder 1",
            "rejectResponderTermination": true,
            "selection": null,
            "style": [Array],
            "text": "",
            "textBreakStrategy": undefined,
            "underlineColorAndroid": "transparent"
        },
        "ref": [Function forwardRef],
        "return": {
            "_debugHookTypes": null,
            "_debugID": 31292,
            "_debugNeedsRemount": false,
            "_debugOwner": [FiberNode],
            "_debugSource": [Object],
            "actualDuration": 0.5718999999808148,
            "actualStartTime": 444209.2045,
            "alternate": [FiberNode],
            "child": [Circular],
            "childLanes": 0,
            "dependencies": null,
            "elementType": [Function TouchableWithoutFeedback],
            "firstEffect": [Circular],
            "flags": 5,
            "index": 0,
            "key": null,
            "lanes": 0,
            "lastEffect": [Circular],
            "memoizedProps": [Object],
            "memoizedState": [Object],
            "mode": 8,
            "nextEffect": null,
            "pendingProps": [Object],
            "ref": null,
            "return": [FiberNode],
            "selfBaseDuration": 0.2691999999806285,
            "sibling": null,
            "stateNode": [TouchableWithoutFeedback],
            "tag": 1,
            "treeBaseDuration": 0.3690000000060536,
            "type": [Function TouchableWithoutFeedback],
            "updateQueue": [Object]
        },
        "selfBaseDuration": 0.0998000000254251,
        "sibling": null,
        "stateNode": {
            "_children": [Array],
            "_internalFiberInstanceHandleDEV": [Circular],
            "_nativeTag": 1395,
            "clear": [Function clear],
            "getNativeRef": [Function getNativeRef],
            "isFocused": [Function isFocused],
            "viewConfig": [Object]
        },
        "tag": 5,
        "treeBaseDuration": 0.0998000000254251,
        "type": "AndroidTextInput",
        "updateQueue": null
    },
    "_dispatchListeners": [Function onSubmitEditing],
    "_targetInst": {
        "_debugHookTypes": null,
        "_debugID": 31294,
        "_debugNeedsRemount": false,
        "_debugOwner": {
            "_debugHookTypes": [Array],
            "_debugID": 31288,
            "_debugNeedsRemount": false,
            "_debugOwner": [FiberNode],
            "_debugSource": [Object],
            "actualDuration": 1.3340999999199994,
            "actualStartTime": 444208.4736,
            "alternate": [FiberNode],
            "child": [FiberNode],
            "childLanes": 0,
            "dependencies": null,
            "elementType": [Function InternalTextInput],
            "firstEffect": [Circular],
            "flags": 5,
            "index": 0,
            "key": null,
            "lanes": 0,
            "lastEffect": [FiberNode],
            "memoizedProps": [Object],
            "memoizedState": [Object],
            "mode": 8,
            "nextEffect": null,
            "pendingProps": [Object],
            "ref": null,
            "return": [FiberNode],
            "selfBaseDuration": 0.5415999999968335,
            "sibling": null,
            "stateNode": null,
            "tag": 0,
            "treeBaseDuration": 1.017200000002049,
            "type": [Function InternalTextInput],
            "updateQueue": [Object]
        },
        "_debugSource": {
            "columnNumber": 7,
            "fileName": "C:\\Users\\gians\\Desktop\\CS\\WebDev\\sikhStuff\\SanthiyaPothi\\node_modules\\react-native\\Libraries\\Components\\TextInput\\TextInput.js",
            "lineNumber": 1121
        },
        "actualDuration": 0.25760000001173466,
        "actualStartTime": 444209.5192,
        "alternate": {
            "_debugHookTypes": null,
            "_debugID": 31294,
            "_debugNeedsRemount": false,
            "_debugOwner": [FiberNode],
            "_debugSource": [Object],
            "actualDuration": 0.15590000001247972,
            "actualStartTime": 444170.704,
            "alternate": [Circular],
            "child": null,
            "childLanes": 0,
            "dependencies": null,
            "elementType": "AndroidTextInput",
            "firstEffect": null,
            "flags": 132,
            "index": 0,
            "key": null,
            "lanes": 0,
            "lastEffect": null,
            "memoizedProps": [Object],
            "memoizedState": null,
            "mode": 8,
            "nextEffect": null,
            "pendingProps": [Object],
            "ref": [Function forwardRef],
            "return": [FiberNode],
            "selfBaseDuration": 0.10490000003483146,
            "sibling": null,
            "stateNode": [ReactNativeFiberHostComponent],
            "tag": 5,
            "treeBaseDuration": 0.10490000003483146,
            "type": "AndroidTextInput",
            "updateQueue": null
        },
        "child": null,
        "childLanes": 0,
        "dependencies": null,
        "elementType": "AndroidTextInput",
        "firstEffect": null,
        "flags": 132,
        "index": 0,
        "key": null,
        "lanes": 0,
        "lastEffect": null,
        "memoizedProps": {
            "accessible": true,
            "allowFontScaling": true,
            "autoCapitalize": "sentences",
            "blurOnSubmit": true,
            "children": undefined,
            "disableFullscreenUI": undefined,
            "focusable": true,
            "forwardedRef": null,
            "mostRecentEventCount": 5,
            "onBlur": [Function _onBlur],
            "onChange": [Function _onChange],
            "onClick": [Function onClick],
            "onFocus": [Function _onFocus],
            "onResponderGrant": [Function onResponderGrant],
            "onResponderMove": [Function onResponderMove],
            "onResponderRelease": [Function onResponderRelease],
            "onResponderTerminate": [Function onResponderTerminate],
            "onResponderTerminationRequest": [Function onResponderTerminationRequest],
            "onScroll": [Function _onScroll],
            "onSelectionChange": [Function _onSelectionChange],
            "onStartShouldSetResponder": [Function onStartShouldSetResponder],
            "onSubmitEditing": [Function onSubmitEditing],
            "placeholder": "exp: Folder 1",
            "rejectResponderTermination": true,
            "selection": null,
            "style": [Array],
            "text": "",
            "textBreakStrategy": undefined,
            "underlineColorAndroid": "transparent"
        },
        "memoizedState": null,
        "mode": 8,
        "nextEffect": null,
        "pendingProps": {
            "accessible": true,
            "allowFontScaling": true,
            "autoCapitalize": "sentences",
            "blurOnSubmit": true,
            "children": undefined,
            "disableFullscreenUI": undefined,
            "focusable": true,
            "forwardedRef": null,
            "mostRecentEventCount": 5,
            "onBlur": [Function _onBlur],
            "onChange": [Function _onChange],
            "onClick": [Function onClick],
            "onFocus": [Function _onFocus],
            "onResponderGrant": [Function onResponderGrant],
            "onResponderMove": [Function onResponderMove],
            "onResponderRelease": [Function onResponderRelease],
            "onResponderTerminate": [Function onResponderTerminate],
            "onResponderTerminationRequest": [Function onResponderTerminationRequest],
            "onScroll": [Function _onScroll],
            "onSelectionChange": [Function _onSelectionChange],
            "onStartShouldSetResponder": [Function onStartShouldSetResponder],
            "onSubmitEditing": [Function onSubmitEditing],
            "placeholder": "exp: Folder 1",
            "rejectResponderTermination": true,
            "selection": null,
            "style": [Array],
            "text": "",
            "textBreakStrategy": undefined,
            "underlineColorAndroid": "transparent"
        },
        "ref": [Function forwardRef],
        "return": {
            "_debugHookTypes": null,
        "_debugID": 31292,
        "_debugNeedsRemount": false,
        "_debugOwner": [FiberNode],
        "_debugSource": [Object],
        "actualDuration": 0.5718999999808148,
        "actualStartTime": 444209.2045,
        "alternate": [FiberNode],
        "child": [Circular],
        "childLanes": 0,
        "dependencies": null,
        "elementType": [Function TouchableWithoutFeedback],
        "firstEffect": [Circular],
        "flags": 5,
        "index": 0,
        "key": null,
        "lanes": 0,
        "lastEffect": [Circular],
        "memoizedProps": [Object],
        "memoizedState": [Object],
        "mode": 8,
        "nextEffect": null,
        "pendingProps": [Object],
        "ref": null,
        "return": [FiberNode],
        "selfBaseDuration": 0.2691999999806285,
        "sibling": null,
        "stateNode": [TouchableWithoutFeedback],
        "tag": 1,
        "treeBaseDuration": 0.3690000000060536,
        "type": [Function TouchableWithoutFeedback],
        "updateQueue": [Object]},
        "selfBaseDuration": 0.0998000000254251,
        "sibling": null,
        "stateNode": {
            "_children": [Array],
        "_internalFiberInstanceHandleDEV": [Circular],
        "_nativeTag": 1395,
        "clear": [Function clear],
        "getNativeRef": [Function getNativeRef],
        "isFocused": [Function isFocused],
        "viewConfig": [Object]},
        "tag": 5,
        "treeBaseDuration": 0.0998000000254251,
        "type": "AndroidTextInput",
        "updateQueue": null
    },
    "bubbles": undefined,
    "cancelable": undefined,
    "currentTarget": {
        "_children": [],
    "_internalFiberInstanceHandleDEV": {
        "_debugHookTypes": null,
    "_debugID": 31294,
    "_debugNeedsRemount": false,
    "_debugOwner": [FiberNode],
    "_debugSource": [Object],
    "actualDuration": 0.25760000001173466,
    "actualStartTime": 444209.5192,
    "alternate": [FiberNode],
    "child": null,
    "childLanes": 0,
    "dependencies": null,
    "elementType": "AndroidTextInput",
    "firstEffect": null,
    "flags": 132,
    "index": 0,
    "key": null,
    "lanes": 0,
    "lastEffect": null,
    "memoizedProps": [Object],
    "memoizedState": null,
    "mode": 8,
    "nextEffect": null,
    "pendingProps": [Object],
    "ref": [Function forwardRef],
    "return": [FiberNode],
    "selfBaseDuration": 0.0998000000254251,
    "sibling": null,
    "stateNode": [Circular],
    "tag": 5,
    "treeBaseDuration": 0.0998000000254251,
    "type": "AndroidTextInput",
    "updateQueue": null},
    "_nativeTag": 1395,
    "clear": [Function clear],
    "getNativeRef": [Function getNativeRef],
    "isFocused": [Function isFocused],
    "viewConfig": {
        "Commands": [Object],
        "Constants": [Object],
        "NativeProps": [Object],
        "bubblingEventTypes": [Object],
        "directEventTypes": [Object],
        "uiViewClassName": "AndroidTextInput",
        "validAttributes": [Object]}
    },
    "defaultPrevented": undefined,
    "dispatchConfig": {
        "phasedRegistrationNames": {
        "bubbled": "onSubmitEditing",
        "captured": "onSubmitEditingCapture"
        }
    },
    "eventPhase": undefined,
    "isDefaultPrevented": [Function functionThatReturnsFalse],
    "isPropagationStopped": [Function functionThatReturnsFalse],
    "isTrusted": undefined,
    "nativeEvent": {
        "target": 1395,
        "text": "cager"
    },
    "target": {
        "_children": [],
    "_internalFiberInstanceHandleDEV": {
        "_debugHookTypes": null,
    "_debugID": 31294,
    "_debugNeedsRemount": false,
    "_debugOwner": [FiberNode],
    "_debugSource": [Object],
    "actualDuration": 0.25760000001173466,
    "actualStartTime": 444209.5192,
    "alternate": [FiberNode],
    "child": null,
    "childLanes": 0,
    "dependencies": null,
    "elementType": "AndroidTextInput",
    "firstEffect": null,
    "flags": 132,
    "index": 0,
    "key": null,
    "lanes": 0,
    "lastEffect": null,
    "memoizedProps": [Object],
    "memoizedState": null,
    "mode": 8,
    "nextEffect": null,
    "pendingProps": [Object],
    "ref": [Function forwardRef],
    "return": [FiberNode],
    "selfBaseDuration": 0.0998000000254251,
    "sibling": null,
    "stateNode": [Circular],
    "tag": 5,
    "treeBaseDuration": 0.0998000000254251,
    "type": "AndroidTextInput",
    "updateQueue": null},
    "_nativeTag": 1395,
    "clear": [Function clear],
    "getNativeRef": [Function getNativeRef],
    "isFocused": [Function isFocused],
    "viewConfig": {
        "Commands": [Object],
    "Constants": [Object],
    "NativeProps": [Object],
    "bubblingEventTypes": [Object],
    "directEventTypes": [Object],
    "uiViewClassName": "AndroidTextInput",
    "validAttributes": [Object]}},
    "timeStamp": 1641527132176,
    "type": undefined
}


pdfRef
{
  "current": {
    "_downloadFile": [Function _callee7],
    "_loadFromSource": [Function anonymous],
    "_mounted": true,
    "_onChange": [Function anonymous],
    "_onError": [Function anonymous],
    "_prepareFile": [Function _callee3],
    "_reactInternalInstance": {},
    "_reactInternals": {"_debugHookTypes": null, "_debugID": 9440, "_debugNeedsRemount": false, "_debugOwner": [FiberNode], "_debugSource": [Object], "actualDuration": 0.00739598274230957, "actualStartTime": 1189036105.592064, "alternate": [FiberNode], "child": [FiberNode], "childLanes": 0, "dependencies": null, "elementType": [Function Pdf], "firstEffect": null, "flags": 0, "index": 0, "key": null, "lanes": 0, "lastEffect": null, "memoizedProps": [Object], "memoizedState": [Object], "mode": 8, "nextEffect": null, "pendingProps": [Object], "ref": [Circular], "return": [FiberNode], "selfBaseDuration": 0.2958850860595703, "sibling": [FiberNode], "stateNode": [Circular], "tag": 1, "treeBaseDuration": 0.4271359443664551, "type": [Function Pdf], "updateQueue": [Object]},
    "_root": {"_children": [Array], "_internalFiberInstanceHandleDEV": [FiberNode], "_nativeTag": 935, "viewConfig": [Object]},
    "_unlinkFile": [Function _callee8],
    "context": {},
    "lastRNBFTask": null,
    "props": {"activityIndicator": <ActivityIndicator … />, "activityIndicatorProps": [Object], "enableAnnotationRendering": true, "enableAntialiasing": true, "enablePaging": false, "enableRTL": false, "fitPolicy": 2, "horizontal": false, "maxScale": 3, "minScale": 1, "onError": [Function onError], "onLoadComplete": [Function onLoadComplete], "onLoadProgress": [Function onLoadProgress], "onPageChanged": [Function onPageChanged], "onPageSingleTap": [Function onPageSingleTap], "onPressLink": [Function onPressLink], "onScaleChanged": [Function onScaleChanged], "page": 1, "password": "", "scale": 1, "singlePage": false, "source": [Object], "spacing": 10, "style": [Object], "trustAllCerts": true, "usePDFKit": true}, 
    "refs": {},
    "setNativeProps": [Function anonymous],
    "state": {"isDownloaded": true, "isSupportPDFKit": -1, "path": "/data/user/0/com.larrivarpothi/cache/cc177d8ff1b116a0eb2f2d2dfcf1287c52828a13.pdf", "progress": 1},
    "updater": {"enqueueForceUpdate": [Function enqueueForceUpdate], "enqueueReplaceState": [Function enqueueReplaceState], "enqueueSetState": [Function enqueueSetState], "isMounted": [Function isMounted]}
  }
}

