{"_dispatchInstances": {"_debugHookTypes": null,
 "_debugID": 22718,
 "_debugNeedsRemount": false,
 "_debugOwner": {"_debugHookTypes": [Array],
 "_debugID": 22712,
 "_debugNeedsRemount": false,
 "_debugOwner": [FiberNode],
 "_debugSource": [Object],
 "actualDuration": 0.7379999980330467,
 "actualStartTime": 6145104.9905,
 "alternate": [FiberNode],
 "child": [FiberNode],
 "childLanes": 0,
 "dependencies": null,
 "elementType": [Function InternalTextInput],
 "firstEffect": [Circular],
 "flags": 5,
 "index": 0,
 "key": null,
 "lanes": 0,
 "lastEffect": [FiberNode],
 "memoizedProps": [Object],
 "memoizedState": [Object],
 "mode": 8,
 "nextEffect": null,
 "pendingProps": [Object],
 "ref": null,
 "return": [FiberNode],
 "selfBaseDuration": 0.3011000007390976,
 "sibling": null,
 "stateNode": null,
 "tag": 0,
 "treeBaseDuration": 0.6612999998033047,
 "type": [Function InternalTextInput],
 "updateQueue": [Object]},
 "_debugSource": {"columnNumber": 7,
 "fileName": "C:\\Users\\gians\\Desktop\\CS\\WebDev\\sikhStuff\\SanthiyaPothi\\node_modules\\react-native\\Libraries\\Components\\TextInput\\TextInput.js",
 "lineNumber": 1121},
 "actualDuration": 0.06259999889880419,
 "actualStartTime": 6145105.661,
 "alternate": {"_debugHookTypes": null,
 "_debugID": 22718,
 "_debugNeedsRemount": false,
 "_debugOwner": [FiberNode],
 "_debugSource": [Object],
 "actualDuration": 0.08590000029653311,
 "actualStartTime": 6145085.3196,
 "alternate": [Circular],
 "child": null,
 "childLanes": 0,
 "dependencies": null,
 "elementType": "AndroidTextInput",
 "firstEffect": null,
 "flags": 132,
 "index": 0,
 "key": null,
 "lanes": 0,
 "lastEffect": null,
 "memoizedProps": [Object],
 "memoizedState": null,
 "mode": 8,
 "nextEffect": null,
 "pendingProps": [Object],
 "ref": [Function forwardRef],
 "return": [FiberNode],
 "selfBaseDuration": 0.05360000021755695,
 "sibling": null,
 "stateNode": [ReactNativeFiberHostComponent],
 "tag": 5,
 "treeBaseDuration": 0.05360000021755695,
 "type": "AndroidTextInput",
 "updateQueue": null},
 "child": null,
 "childLanes": 0,
 "dependencies": null,
 "elementType": "AndroidTextInput",
 "firstEffect": null,
 "flags": 132,
 "index": 0,
 "key": null,
 "lanes": 0,
 "lastEffect": null,
 "memoizedProps": {"accessible": true,
 "allowFontScaling": true,
 "autoCapitalize": "sentences",
 "blurOnSubmit": true,
 "children": undefined,
 "disableFullscreenUI": undefined,
 "focusable": true,
 "forwardedRef": null,
 "keyboardType": "numeric",
 "mostRecentEventCount": 17,
 "onBlur": [Function _onBlur],
 "onChange": [Function _onChange],
 "onChangeText": [Function onChangeText],
 "onClick": [Function onClick],
 "onFocus": [Function _onFocus],
 "onResponderGrant": [Function onResponderGrant],
 "onResponderMove": [Function onResponderMove],
 "onResponderRelease": [Function onResponderRelease],
 "onResponderTerminate": [Function onResponderTerminate],
 "onResponderTerminationRequest": [Function onResponderTerminationRequest],
 "onScroll": [Function _onScroll],
 "onSelectionChange": [Function _onSelectionChange],
 "onStartShouldSetResponder": [Function onStartShouldSetResponder],
 "onSubmitEditing": [Function onSubmitEditing],
 "placeholder": "ex: 5",
 "rejectResponderTermination": true,
 "selection": null,
 "style": [Array],
 "text": "56",
 "textBreakStrategy": undefined,
 "underlineColorAndroid": "transparent",
 "value": "56"},
 "memoizedState": null,
 "mode": 8,
 "nextEffect": null,
 "pendingProps": {"accessible": true,
 "allowFontScaling": true,
 "autoCapitalize": "sentences",
 "blurOnSubmit": true,
 "children": undefined,
 "disableFullscreenUI": undefined,
 "focusable": true,
 "forwardedRef": null,
 "keyboardType": "numeric",
 "mostRecentEventCount": 17,
 "onBlur": [Function _onBlur],
 "onChange": [Function _onChange],
 "onChangeText": [Function onChangeText],
 "onClick": [Function onClick],
 "onFocus": [Function _onFocus],
 "onResponderGrant": [Function onResponderGrant],
 "onResponderMove": [Function onResponderMove],
 "onResponderRelease": [Function onResponderRelease],
 "onResponderTerminate": [Function onResponderTerminate],
 "onResponderTerminationRequest": [Function onResponderTerminationRequest],
 "onScroll": [Function _onScroll],
 "onSelectionChange": [Function _onSelectionChange],
 "onStartShouldSetResponder": [Function onStartShouldSetResponder],
 "onSubmitEditing": [Function onSubmitEditing],
 "placeholder": "ex: 5",
 "rejectResponderTermination": true,
 "selection": null,
 "style": [Array],
 "text": "56",
 "textBreakStrategy": undefined,
 "underlineColorAndroid": "transparent",
 "value": "56"},
 "ref": [Function forwardRef],
 "return": {"_debugHookTypes": null,
 "_debugID": 22716,
 "_debugNeedsRemount": false,
 "_debugOwner": [FiberNode],
 "_debugSource": [Object],
 "actualDuration": 0.35719999857246876,
 "actualStartTime": 6145105.3639,
 "alternate": [FiberNode],
 "child": [Circular],
 "childLanes": 0,
 "dependencies": null,
 "elementType": [Function TouchableWithoutFeedback],
 "firstEffect": [Circular],
 "flags": 5,
 "index": 0,
 "key": null,
 "lanes": 0,
 "lastEffect": [Circular],
 "memoizedProps": [Object],
 "memoizedState": [Object],
 "mode": 8,
 "nextEffect": null,
 "pendingProps": [Object],
 "ref": null,
 "return": [FiberNode],
 "selfBaseDuration": 0.27940000034868717,
 "sibling": null,
 "stateNode": [TouchableWithoutFeedback],
 "tag": 1,
 "treeBaseDuration": 0.3198999995365739,
 "type": [Function TouchableWithoutFeedback],
 "updateQueue": [Object]},
 "selfBaseDuration": 0.040499999187886715,
 "sibling": null,
 "stateNode": {"_children": [Array],
 "_internalFiberInstanceHandleDEV": [Circular],
 "_nativeTag": 3085,
 "clear": [Function clear],
 "getNativeRef": [Function getNativeRef],
 "isFocused": [Function isFocused],
 "viewConfig": [Object]},
 "tag": 5,
 "treeBaseDuration": 0.040499999187886715,
 "type": "AndroidTextInput",
 "updateQueue": null},
 "_dispatchListeners": [Function onSubmitEditing],
 "_targetInst": {"_debugHookTypes": null,
 "_debugID": 22718,
 "_debugNeedsRemount": false,
 "_debugOwner": {"_debugHookTypes": [Array],
 "_debugID": 22712,
 "_debugNeedsRemount": false,
 "_debugOwner": [FiberNode],
 "_debugSource": [Object],
 "actualDuration": 0.7379999980330467,
 "actualStartTime": 6145104.9905,
 "alternate": [FiberNode],
 "child": [FiberNode],
 "childLanes": 0,
 "dependencies": null,
 "elementType": [Function InternalTextInput],
 "firstEffect": [Circular],
 "flags": 5,
 "index": 0,
 "key": null,
 "lanes": 0,
 "lastEffect": [FiberNode],
 "memoizedProps": [Object],
 "memoizedState": [Object],
 "mode": 8,
 "nextEffect": null,
 "pendingProps": [Object],
 "ref": null,
 "return": [FiberNode],
 "selfBaseDuration": 0.3011000007390976,
 "sibling": null,
 "stateNode": null,
 "tag": 0,
 "treeBaseDuration": 0.6612999998033047,
 "type": [Function InternalTextInput],
 "updateQueue": [Object]},
 "_debugSource": {"columnNumber": 7,
 "fileName": "C:\\Users\\gians\\Desktop\\CS\\WebDev\\sikhStuff\\SanthiyaPothi\\node_modules\\react-native\\Libraries\\Components\\TextInput\\TextInput.js",
 "lineNumber": 1121},
 "actualDuration": 0.06259999889880419,
 "actualStartTime": 6145105.661,
 "alternate": {"_debugHookTypes": null,
 "_debugID": 22718,
 "_debugNeedsRemount": false,
 "_debugOwner": [FiberNode],
 "_debugSource": [Object],
 "actualDuration": 0.08590000029653311,
 "actualStartTime": 6145085.3196,
 "alternate": [Circular],
 "child": null,
 "childLanes": 0,
 "dependencies": null,
 "elementType": "AndroidTextInput",
 "firstEffect": null,
 "flags": 132,
 "index": 0,
 "key": null,
 "lanes": 0,
 "lastEffect": null,
 "memoizedProps": [Object],
 "memoizedState": null,
 "mode": 8,
 "nextEffect": null,
 "pendingProps": [Object],
 "ref": [Function forwardRef],
 "return": [FiberNode],
 "selfBaseDuration": 0.05360000021755695,
 "sibling": null,
 "stateNode": [ReactNativeFiberHostComponent],
 "tag": 5,
 "treeBaseDuration": 0.05360000021755695,
 "type": "AndroidTextInput",
 "updateQueue": null},
 "child": null,
 "childLanes": 0,
 "dependencies": null,
 "elementType": "AndroidTextInput",
 "firstEffect": null,
 "flags": 132,
 "index": 0,
 "key": null,
 "lanes": 0,
 "lastEffect": null,
 "memoizedProps": {"accessible": true,
 "allowFontScaling": true,
 "autoCapitalize": "sentences",
 "blurOnSubmit": true,
 "children": undefined,
 "disableFullscreenUI": undefined,
 "focusable": true,
 "forwardedRef": null,
 "keyboardType": "numeric",
 "mostRecentEventCount": 17,
 "onBlur": [Function _onBlur],
 "onChange": [Function _onChange],
 "onChangeText": [Function onChangeText],
 "onClick": [Function onClick],
 "onFocus": [Function _onFocus],
 "onResponderGrant": [Function onResponderGrant],
 "onResponderMove": [Function onResponderMove],
 "onResponderRelease": [Function onResponderRelease],
 "onResponderTerminate": [Function onResponderTerminate],
 "onResponderTerminationRequest": [Function onResponderTerminationRequest],
 "onScroll": [Function _onScroll],
 "onSelectionChange": [Function _onSelectionChange],
 "onStartShouldSetResponder": [Function onStartShouldSetResponder],
 "onSubmitEditing": [Function onSubmitEditing],
 "placeholder": "ex: 5",
 "rejectResponderTermination": true,
 "selection": null,
 "style": [Array],
 "text": "56",
 "textBreakStrategy": undefined,
 "underlineColorAndroid": "transparent",
 "value": "56"},
 "memoizedState": null,
 "mode": 8,
 "nextEffect": null,
 "pendingProps": {"accessible": true,
 "allowFontScaling": true,
 "autoCapitalize": "sentences",
 "blurOnSubmit": true,
 "children": undefined,
 "disableFullscreenUI": undefined,
 "focusable": true,
 "forwardedRef": null,
 "keyboardType": "numeric",
 "mostRecentEventCount": 17,
 "onBlur": [Function _onBlur],
 "onChange": [Function _onChange],
 "onChangeText": [Function onChangeText],
 "onClick": [Function onClick],
 "onFocus": [Function _onFocus],
 "onResponderGrant": [Function onResponderGrant],
 "onResponderMove": [Function onResponderMove],
 "onResponderRelease": [Function onResponderRelease],
 "onResponderTerminate": [Function onResponderTerminate],
 "onResponderTerminationRequest": [Function onResponderTerminationRequest],
 "onScroll": [Function _onScroll],
 "onSelectionChange": [Function _onSelectionChange],
 "onStartShouldSetResponder": [Function onStartShouldSetResponder],
 "onSubmitEditing": [Function onSubmitEditing],
 "placeholder": "ex: 5",
 "rejectResponderTermination": true,
 "selection": null,
 "style": [Array],
 "text": "56",
 "textBreakStrategy": undefined,
 "underlineColorAndroid": "transparent",
 "value": "56"},
 "ref": [Function forwardRef],
 "return": {"_debugHookTypes": null,
 "_debugID": 22716,
 "_debugNeedsRemount": false,
 "_debugOwner": [FiberNode],
 "_debugSource": [Object],
 "actualDuration": 0.35719999857246876,
 "actualStartTime": 6145105.3639,
 "alternate": [FiberNode],
 "child": [Circular],
 "childLanes": 0,
 "dependencies": null,
 "elementType": [Function TouchableWithoutFeedback],
 "firstEffect": [Circular],
 "flags": 5,
 "index": 0,
 "key": null,
 "lanes": 0,
 "lastEffect": [Circular],
 "memoizedProps": [Object],
 "memoizedState": [Object],
 "mode": 8,
 "nextEffect": null,
 "pendingProps": [Object],
 "ref": null,
 "return": [FiberNode],
 "selfBaseDuration": 0.27940000034868717,
 "sibling": null,
 "stateNode": [TouchableWithoutFeedback],
 "tag": 1,
 "treeBaseDuration": 0.3198999995365739,
 "type": [Function TouchableWithoutFeedback],
 "updateQueue": [Object]},
 "selfBaseDuration": 0.040499999187886715,
 "sibling": null,
 "stateNode": {"_children": [Array],
 "_internalFiberInstanceHandleDEV": [Circular],
 "_nativeTag": 3085,
 "clear": [Function clear],
 "getNativeRef": [Function getNativeRef],
 "isFocused": [Function isFocused],
 "viewConfig": [Object]},
 "tag": 5,
 "treeBaseDuration": 0.040499999187886715,
 "type": "AndroidTextInput",
 "updateQueue": null},
 "bubbles": undefined,
 "cancelable": undefined,
 "currentTarget": {"_children": [],
 "_internalFiberInstanceHandleDEV": {"_debugHookTypes": null,
 "_debugID": 22718,
 "_debugNeedsRemount": false,
 "_debugOwner": [FiberNode],
 "_debugSource": [Object],
 "actualDuration": 0.06259999889880419,
 "actualStartTime": 6145105.661,
 "alternate": [FiberNode],
 "child": null,
 "childLanes": 0,
 "dependencies": null,
 "elementType": "AndroidTextInput",
 "firstEffect": null,
 "flags": 132,
 "index": 0,
 "key": null,
 "lanes": 0,
 "lastEffect": null,
 "memoizedProps": [Object],
 "memoizedState": null,
 "mode": 8,
 "nextEffect": null,
 "pendingProps": [Object],
 "ref": [Function forwardRef],
 "return": [FiberNode],
 "selfBaseDuration": 0.040499999187886715,
 "sibling": null,
 "stateNode": [Circular],
 "tag": 5,
 "treeBaseDuration": 0.040499999187886715,
 "type": "AndroidTextInput",
 "updateQueue": null},
 "_nativeTag": 3085,
 "clear": [Function clear],
 "getNativeRef": [Function getNativeRef],
 "isFocused": [Function isFocused],
 "viewConfig": {"Commands": [Object],
 "Constants": [Object],
 "NativeProps": [Object],
 "bubblingEventTypes": [Object],
 "directEventTypes": [Object],
 "uiViewClassName": "AndroidTextInput",
 "validAttributes": [Object]}},
 "defaultPrevented": undefined,
 "dispatchConfig": {"phasedRegistrationNames": {"bubbled": "onSubmitEditing",
 "captured": "onSubmitEditingCapture"}},
 "eventPhase": undefined,
 "isDefaultPrevented": [Function functionThatReturnsFalse],
 "isPropagationStopped": [Function functionThatReturnsFalse],
 "isTrusted": undefined,
 "nativeEvent": {"target": 3085,
 "text": "56"},
 "target": {"_children": [],
 "_internalFiberInstanceHandleDEV": {"_debugHookTypes": null,
 "_debugID": 22718,
 "_debugNeedsRemount": false,
 "_debugOwner": [FiberNode],
 "_debugSource": [Object],
 "actualDuration": 0.06259999889880419,
 "actualStartTime": 6145105.661,
 "alternate": [FiberNode],
 "child": null,
 "childLanes": 0,
 "dependencies": null,
 "elementType": "AndroidTextInput",
 "firstEffect": null,
 "flags": 132,
 "index": 0,
 "key": null,
 "lanes": 0,
 "lastEffect": null,
 "memoizedProps": [Object],
 "memoizedState": null,
 "mode": 8,
 "nextEffect": null,
 "pendingProps": [Object],
 "ref": [Function forwardRef],
 "return": [FiberNode],
 "selfBaseDuration": 0.040499999187886715,
 "sibling": null,
 "stateNode": [Circular],
 "tag": 5,
 "treeBaseDuration": 0.040499999187886715,
 "type": "AndroidTextInput",
 "updateQueue": null},
 "_nativeTag": 3085,
 "clear": [Function clear],
 "getNativeRef": [Function getNativeRef],
 "isFocused": [Function isFocused],
 "viewConfig": {"Commands": [Object],
 "Constants": [Object],
 "NativeProps": [Object],
 "bubblingEventTypes": [Object],
 "directEventTypes": [Object],
 "uiViewClassName": "AndroidTextInput",
 "validAttributes": [Object]}},
 "timeStamp": 1640891052765,
 "type": undefined}
